### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by alexanderzeillinger** [eclipse-labs/FightCode-OpenBot#1]
I am not sure if you intend to have contributions from other people but right now this is rather hard. You should
- Deobfuscate variables
- Use English variable names (not "poyavilsa", "poteryal", etc.)
- Add comments to explain what the bot is doing

On another note you can install this Chrome Extension:
https://chrome.google.com/webstore/detail/custom-javascript-for-web/poakhlngfciodnhlhhgnaaelnpjljija

and add this code to it:
https://gist.github.com/alexanderzeillinger/300a6fa0c718fc157d0b 

It will resize the training arena to the same size as the real arena, add a refresh button and add OpenBot to the dropdown of available opponents. Overall a much better experience.

**Comment by SYZYGY-DEV333** [comment]
Thank you sir, I shall get to that soon.
